name: integration

on: [push, pull_request]

jobs:

  checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        check: [bluecheck, doc8, docs, flake8, isortcheck, rstcheck]
  
    steps:
    - uses: actions/checkout@v3
    - run: wget https://dl.typesense.org/releases/0.24.1/typesense-server-0.24.1-linux-amd64.tar.gz
    - run: tar -xzf typesense-server-0.24.1-linux-amd64.tar.gz
    - run: split -d -n 2 typesense-server typesense-server.bin.
    - run: mkdir -p chunk1/src/typesense_server_wrapper
    - run: mv typesense-server.bin.00 chunk1/src/typesense_server_wrapper/
    - run: mkdir -p chunk2/src/typesense_server_wrapper
    - run: mv typesense-server.bin.01 chunk2/src/typesense_server_wrapper/
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install tox
    - name: Run checks with tox
      run: |
        tox -e ${{ matrix.check }}
  
  tests:
    needs: checks
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
  
    steps:
    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
  
    - uses: actions/checkout@v3
    - run: wget https://dl.typesense.org/releases/0.24.1/typesense-server-0.24.1-linux-amd64.tar.gz
    - run: tar -xzf typesense-server-0.24.1-linux-amd64.tar.gz
    - run: split -d -n 2 typesense-server typesense-server.bin.
    - run: split -d -n 2 typesense-server typesense-server.bin.
    - run: mkdir -p chunk1/src/typesense_server_wrapper
    - run: mv typesense-server.bin.00 chunk1/src/typesense_server_wrapper/
    - run: mkdir -p chunk2/src/typesense_server_wrapper
    - run: mv typesense-server.bin.01 chunk2/src/typesense_server_wrapper/
  
    - name: Install tox
      run: |
        pip install --upgrade pip
        pip install tox
  
    - name: Test with tox
      run: tox -e py
